name: APOC Auto Cherry Picking
on:
  pull_request_target:
    types: [closed]
    branches:
      - 'dev'
jobs:
  cherry-pick:
    strategy:
      fail-fast: false
      matrix:
        target-branch: [
          {name: '4.4', comment: '961175996'}
        ]
    runs-on: ubuntu-latest
    name: cherry-pick
    if: github.event.pull_request.merged == true
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Create PR to branch ${{ matrix.target-branch.name }}
        uses: conker84/github-action-cherry-pick@0.1.2
        with:
          pr_branch: ${{ matrix.target-branch.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.NEO4J_OSS_BUILD_GH_TOKEN }}
          #          GITBOT_EMAIL: <BOT_EMAIL>
          DRY_RUN: false
      - name: Add commit-id to comment in case the previous step fails
        uses: peter-evans/create-or-update-comment@v1.4.4
        if: ${{ failure() }}
        with:
          comment-id: ${{ matrix.target-branch.comment }}
          body: |
            - `git cherry-pick ${{ github.sha }}`
